import React from 'react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'

import { FormField, Loader } from '../components'

const CreatePost = () => {

    const navigate = useNavigate();

    const [form, setForm] = useState({
        name: '',
        prompt: '',
        photo: ''
    });

    const [generatingImage, setGeneratingImage] = useState(false);
    const [loading, setLoading] = useState(false);

    const handleSubmit = () => {}

    const handleChange = (event) => {}

  return (
    <section className='max-w-7xl mx-auto'>
        <div>
            <h1 className='font-extrabold text-[#222328] text-[32px]'>Create
            </h1>
            <p className='mt-2 text-[#666e75] text-[16px] max-w [500px]'>Create imaginative and visually stunning images generated by DALL-E AI and share them with the Community</p>
        </div>

        <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
            <FormField
                label='Name'
                type='text'
                name='name'
                placeholder='Enter your name'
                value={form.name}
                onChange={handleChange}
            />

            <FormField
                label='Prompt'
                type='text'
                name='prompt'
                value={form.prompt}
                onChange={handleChange}
                placeholder='Enter a prompt'
            />

            <div className='mt-6'>
                <button
                    type='button'
                    className='font-inter font-medium bg-[#6469ff] text-white px-4 py-2 rounded-md'
                    onClick={() => setForm({ ...form, prompt: getRandomPrompt() })}
                >
                    Generate Prompt
                </button>
            </div>

            <div className='mt-6'>
                <FormField
                    label='Photo'
                    type='file'
                    name='photo'
                    value={form.photo}
                    onChange={handleChange}
                    accept='image/*'
                />
            </div>

            <div className='mt-6'>
                <button
                    type='submit'
                    className='font-inter font-medium bg-[#6469ff] text-white px-4 py-2 rounded-md'
                >
                    {loading ? <Loader /> : 'Create Post'}
                </button>
            </div>
        </form>
    </section>
  )
}

export default CreatePost