import React from 'react'
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'

import { preview } from '../assets'
import { getRandomPrompt } from '../utils'

import { FormField, Loader } from '../components'

const CreatePost = () => {

    const navigate = useNavigate();

    const [form, setForm] = useState({
        name: '',
        prompt: '',
        photo: ''
    });

    const [generatingImage, setGeneratingImage] = useState(false);
    const [loading, setLoading] = useState(false);

    const generateImage = () => { }

    const handleSubmit = () => { }

    const handleChange = (event) => {
        setForm({ ...form, [event.target.name]: event.target.value })
    }
    
    const handleSurpriseMe = () => {
        const randomPropmt = getRandomPrompt(form.prompt)
        setForm({ ...form, prompt: randomPropmt })
    }

    return (
        <section className='max-w-7xl mx-auto'>
            <div>
                <h1 className='font-extrabold text-[#222328] text-[32px]'>Create
                </h1>
                <p className='mt-2 text-[#666e75] text-[16px] max-w [500px]'>Create imaginative and visually stunning images generated by DALL-E AI and share them with the Community</p>
            </div>

            <form className='mt-16 max-w-3xl' onSubmit={handleSubmit}>
                <div className='flex flex-col gap-5'>
                    <FormField
                        labelName='Name'
                        type='text'
                        name='name'
                        placeholder='Enter your name'
                        value={form.name}
                        onChange={handleChange}
                    />

                    <FormField
                        labelName='Prompt'
                        type='text'
                        name='prompt'
                        placeholder='Enter a prompt'
                        value={form.prompt}
                        onChange={handleChange}
                    />
                </div>

                <div className='mt-6'>
                    <button
                        type='button'
                        className='text-white bg-black font-medium rounded-md text-sm w-full sm:auto px-5 py-2.5 text-center'
                        onClick={() => setForm({ ...form, prompt: getRandomPrompt() })}
                    >
                        Generate Prompt
                    </button>
                </div>

                <div className='mt-10 relative bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 w-64 p-3 h-64 flex justify-center items-center'>
                    {form.photo ? (
                        <img
                            src={form.photo}
                            alt={form.prompt}
                            className='w-full h-full object-contain' />
                    ) : (
                        <img
                            src={preview}
                            alt='preview'
                            className='w-9/12 h-9/12 object-contain opacity-40' />
                    )}

                    {generatingImage && (
                        <div className='absolute inset-0 z-0 flex justify-center items-center bg-[rgba(0,0,0,0.5)] rounded-lg'>
                            <Loader />
                        </div>
                    )}
                </div>

                <div className='mt-5 flex gap-5'>
                    <button
                        type='button'
                        onClick={generateImage}
                        className='text-white bg-black font-medium rounded-md text-sm w-full sm:auto px-5 py-2.5 text-center'
                    >
                        {generatingImage ? 'Generating...' : 'Generate Image'}
                    </button>
                </div>

                <div className='mt-10'>
                    <p className='mt-2 text-[#666e75] text-[14px]'>Once you have created the image you want, you can share it with others in the community</p>
                    <button
                        type="submit"
                        className='mt-3 text-white bg-black font-medium rounded-md text-sm w-full sm:auto px-5 py-2.5 text-center' >
                        {loading ? 'Sharing...' : 'Share with the community'}
                    </button>
                </div>

            </form>
        </section>
    )
}

export default CreatePost